{
 "title": "Sersync",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "dirname",
    "query": {
     "query": "rsync_status{dirname=~\".*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rsync 同步总数据量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(rsync_total_size_mb)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rsync 同步文件总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(rsync_total_files_sum)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rsync 同步源数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(rsync_status)by (instance,group))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rsync 同步目录数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(rsync_status)by (dirname,group))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "同步文件数量趋势图",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rsync_total_files_sum{dirname=~\"$dirname\"}",
     "legendFormat": "{{dirname}}"
    }
   ]
  },
  {
   "title": "同步文件大小趋势图",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "rsync_total_size_mb{dirname=~\"$dirname\"}",
     "legendFormat": "{{dirname}}"
    }
   ]
  },
  {
   "title": "Rsync 同步详情",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rsync_status{dirname=~\"$dirname\"}",
     "legendFormat": "同步耗时"
    },
    {
     "expr": "rsync_duration_time_sec{dirname=~\"$dirname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rsync_total_size_mb{dirname=~\"$dirname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rsync_start_time{dirname=~\"$dirname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rsync_total_files_sum{dirname=~\"$dirname\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}